version: "3"

services:
    polytrader:
        build: .
        ports: ["8080:8080"]
        depends_on:
            - db
        volumes:
            - ./dist:/usr/src/app/dist
            - ./test:/usr/src/app/test
            - ./static:/usr/src/app/static

    db:
        image: mongo:3.5
        ports: ['27018:27017']
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ../db-polytrader:/data/db

    redis:
        image: redis:4.0.2
