version: "3"

services:
    polytrader:
        build: .
        ports: ["8080:8080"]
        depends_on:
            - db

    price_updater:
        build: price_updater/
        depends_on:
            - db
        volumes:
            - ./price_updater:/usr/src/app

    db:
        image: mongo:3.5
        ports: ['27018:27017']

