version: "3"

services:
    polytrader:
        build: .
        ports: ["8080:8080"]
        depends_on:
            - db
        volumes:
            - ./dist:/usr/src/app/dist
            - ./static:/usr/src/app/static
            - ./views:/usr/src/app/views
            - ./lib:/usr/src/app/lib

    price_updater:
        build: price_updater/
        depends_on:
            - db
        volumes:
            - ./price_updater:/usr/src/app

    db:
        image: mongo:3.5
        ports: ['27018:27017']
        environment:
          - MONGO_DATA_DIR=/data/db
        volumes:
            - ../db-polytrader:/data/db
