version: "2"

services:
    polytrader:
        image: polytrader/polytrader
        fip: 185.207.112.102
        ports: ["80:8080", "443:8443"]
        volumes:
            - certs:/certs
        depends_on:
            - db
            - redis
        links:
            - db
            - redis
        command: node dist/app.js

    db:
        image: mongo:3.5
        environment:
            - MONGO_DATA_DIR=/data/db
        noauto_volume: true
        volumes:
            - dbdata:/data/db

    redis:
        image: redis:4.0.2
        noauto_volume: true
