version: "2"

services:
    polytrader:
        image: polytrader/polytrader
        fip: 185.207.112.102
        ports: ["80:8080", "443:8443"]
        volumes:
            - certs:/certs
            - uploads:/upload
        depends_on:
            - db
            - redis
        links:
            - db
            - redis
        command: node dist/app.js
        environment:
            - MONGO_USERNAME=polytrader
            - MONGO_PASSWORD=Kz0Gxri7qEnn5rmvqzAW
            - NODE_ENV=production

    db:
        image: mongo:3.5
        ports: ["49000:27017"]
        environment:
            - MONGO_DATA_DIR=/data/db
        noauto_volume: true
        volumes:
            - dbdata:/data/db
        command: mongod --auth --bind_ip 0.0.0.0

    redis:
        image: redis:4.0.2
        noauto_volume: true
